// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzejqnkfdorxxnbbbtcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6ZWpxbmtmZG9yeHhuYmJidGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzk0ODgsImV4cCI6MjA2ODk1NTQ4OH0.jOFecIp6Ljj1dH4ooQgqtXJRYAsoWyJfn66OIst5jWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});